<?php include("banner.php") ?>
<?php include("tentang.php") ?>
<?php include("counter.php") ?>
<?php include("destinasi.php") ?>
<?php include("features.php") ?>
<?php include("destinasi_pilihan.php") ?>
<?php include("testimoni.php") ?>
<?php include("teams.php") ?>
<?php $this->load->view('pages/tiket_form/index') ?>
